name: MineHuntPvPLobbyer
version: '1.3'
main: si.f5.stsaria.mineHuntPvPLobbyer.MineHuntPvPLobbyer
# minecraft api version!!!!
api-version: '1.21'

commands:
  matching:
    description: Start matching game
    aliases: [m, matching]
    usage: /matching